name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5

      - name: install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: 'src-tauri'
          shared-key: 'tauri-build'

      - name: install frontend dependencies
        run: npm install

      - name: build rust code for cache
        working-directory: src-tauri
        run: cargo build --release
